openapi: "3.0.2"
info:
  title: KLAY OPEN API
  version: "1.10.0"
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: http://localhost:7151

paths:
  /klay/getHeaderByHash:
    post:
      operationId: getHeaderByHash
      summary: "[getHeaderByHash]"
      description: |
        Returns information about a header by hash. This API works only on RPC call, not on JavaScript console.

        **JSONRPC:** `klay_getHeaderByHash`

        **NOTE:** *This API is supported from Klaytn v1.7.0.*
      tags:
        - klay

      parameters:
        - name: hashOfBlock
          in: query
          description: Hash of a block.
          required: true
          schema:
            type: string
            format: 32-byte DATA

      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../../../components/requests/JsonRpcRequest.yaml#/components/schemas/JsonRpcRequest"
                - $ref: "#/components/schemas/KlayGetHeaderByHashReq"

      responses:
        200:
          description: Returns a header object, or error when no header was found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../../components/responses/JsonRpcResponse.yaml#/components/schemas/JsonRpcResponse"
                  - $ref: "#/components/schemas/KlayGetHeaderByHashResp"

      externalDocs:
        url: https://docs.klaytn.foundation/content/dapp/json-rpc/api-references/klay/block#klay_getHeaderByHash
        description: Klaytn Docs
      x-codeSamples:
        - lang: "curl"
          label: "Curl"
          source:
            $ref: "../../../code-samples/curl/klay/block/getHeaderByHash.sh"
        # - lang: "java"
        #   label: "Java"
        #   source:
        #     $ref: ""
        - lang: "javascript"
          label: "Javascript"
          source:
            $ref: "../../../code-samples/javascript/klay/block/getHeaderByHash.js"
        #- lang: "python"
        #  label: "Python"
        #  source:
        #    $ref: ""

components:
  schemas:
    KlayGetHeaderByHashReq:
      type: object
      required:
        - method
        - params
      properties:
        method:
          type: string
          default: 'klay_getHeaderByHash'
        params:
          type: array
          items:
            anyOf:
              - type: string
                title: hashOfBlock
                format: 32-byte DATA
                description: Hash of a block.
          example:  ["0x1b4"]

    KlayGetHeaderByHashResp:
      type: object
      properties:
        result:
          $ref: "../../../components/schemas/common/Common.yaml#/components/schemas/KlayHeaderObject"

